---
repositories:
  - name: jenkins
    url: https://charts.jenkins.io

releases:
  - name: jenkins
    namespace: jenkins
    chart: jenkins/jenkins
    values:
      - controller:
          tag: "2.277.1-lts"
          javaOpts: >-
            -Xms32m -Xmx512m
            -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap -Dsun.zip.disableMemoryMapping=true
            -XX:+UseParallelGC -XX:MinHeapFreeRatio=5 -XX:MaxHeapFreeRatio=10 -XX:GCTimeRatio=4 -XX:AdaptiveSizePolicyWeight=90
          JCasC:
            defaultConfig: true
          sidecars:
            configAutoReload:
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
          ingress:
            enabled: true
            hostName: jenkins.apps.lab.local
          installPlugins:
            - kubernetes:1.29.2
            - workflow-aggregator:2.6
            - git:4.7.0
            - configuration-as-code:1.47
            - matrix-auth:2.6.6
            - kubernetes-credentials-provider:0.17
            - multibranch-scan-webhook-trigger:1.0.5
            - generic-webhook-trigger:1.72
            - templating-engine:2.0.4
            - docker-workflow:1.26
            - sonar:2.13
            - multibranch-build-strategy-extension:1.0.10
            - ws-cleanup:0.39
        agent:
          enabled: true
          image: jenkins/inbound-agent
          tag: 4.6-1
          workingDir: "/home/jenkins/agent"
          podTemplates:
            docker: |-
              - name: "docker"
                label: "jenkins-docker"
                containers:
                  - name: "docker"
                    image: "docker:19.03"
                    workingDir: "/home/jenkins/agent"
                    command: "sleep"
                    args: "9999999"
                  - name: "docker-daemon"
                    image: "docker:19.03-dind"
                    workingDir: "/home/jenkins/agent"
                    privileged: true
                volumes:
                  - emptyDirVolume:
                      memory: false
                      mountPath: "/var/run"
            maven-jdk-8: |-
              - name: "maven-jdk-8"
                label: "jenkins-maven"
                containers:
                  - name: "maven"
                    image: "maven:3-jdk-8-alpine"
                    workingDir: "/home/jenkins/agent"
                    command: "sleep"
                    args: "9999999"
                volumes:
                  - persistentVolumeClaim:
                      claimName: "maven-repo"
                      mountPath: "/root/.m2/repository"
                      readOnly: false
        persistence:
          enabled: true
          storageClass: local-storage
          size: "10Gi"
          accessMode: ReadWriteOnce
        rbac:
          readSecrets: true