---
repositories:
  - name: jenkins
    url: https://charts.jenkins.io

releases:
  - name: jenkins
    namespace: jenkins
    chart: jenkins/jenkins
    values:
      - controller:
          tag: "2.263.4-lts"
          sidecars:
            configAutoReload:
              resources:
                limits:
                  cpu: 100m
                  memory: 100Mi
                requests:
                  cpu: 50m
                  memory: 50Mi
          ingress:
            enabled: true
            hostName: jenkins.apps.lab.local
          installPlugins:
            - kubernetes
            - workflow-aggregator
            - git
            - configuration-as-code
            - dashboard-view
            - kubernetes-credentials-provider
            - templating-engine
        
        persistence:
          enabled: true
          storageClass: local-storage
          accessMode: "ReadWriteOnce"
          size: "10Gi"
        
        rbac:
          readSecrets: true
