agent {
    on_merge to: develop, {
        build_artifact()
        parallel(build_container_image(), build_helm_package())
        parallel(unit_test(), static_code_analysis(), scan_container_image())
        parallel(publish_container_image(), publish_helm_package())
        // deploy_to dev
    }

    on_commit to: release, {
        build_artifact()
        parallel(build_container_image(), build_helm_package())
        parallel(unit_test(), static_code_analysis(), scan_container_image())
        parallel(publish_container_image(), publish_helm_package())
        // deploy_to test
    }

    on_merge to: master, from: release, {
        // deploy_to prod
    }
}
